export const categories = [
  ['semua','Semua layanan','spark'],['mutawwif','Mutawwif','guide'],['transportasi','Transportasi','car'],['sedekah-wakaf','Sedekah & Wakaf','heart'],['qurban-aqiqah','Qurban & Aqiqah','sun'],['dam','Dam','book']
];
export const catalog = [
 {id:'mutawwif-umrah',category:'mutawwif',name:'Pendamping umrah',tag:'IBADAH DENGAN LEBIH TENANG',image:'mutawwif.webp',imageType:'app',icon:'guide',type:'booking',city:'Makkah',unit:'per layanan',description:'Pendampingan personal dari tawaf, sa’i, hingga tahallul. Sesuaikan ritme perjalanan dengan kebutuhan jemaah.',features:['Bimbingan rangkaian umrah','Kebutuhan keluarga & lansia','Preferensi bahasa pendamping'],included:['Pendampingan rangkaian ibadah sesuai layanan yang disepakati.','Koordinasi titik pertemuan dan jadwal dengan tim Siiru.','Permintaan bahasa serta bantuan mobilitas dapat dicantumkan.'],requirements:['Tentukan tanggal, jumlah jemaah, dan titik pertemuan.','Sampaikan kebutuhan lansia atau pengguna kursi roda.','Nama pendamping, durasi, cakupan, dan tarif dikonfirmasi sebelum pembayaran.'],note:'Transportasi, hotel, dan layanan kursi roda tidak otomatis termasuk.',app:'Chat langsung dengan mutawwif untuk koordinasi setelah pemesanan.',cta:'Atur pendampingan'},
 {id:'transport-private',category:'transportasi',name:'Transportasi pribadi',tag:'DARI KEDATANGAN HINGGA TUJUAN',image:'transport.webp',imageType:'app',icon:'car',type:'booking',city:'Jeddah · Makkah · Madinah',unit:'per perjalanan',description:'Rencanakan transfer bandara atau perjalanan antarkota. Sampaikan jumlah penumpang dan bagasi Anda.',features:['Transfer bandara & antarkota','Pilihan kendaraan sesuai grup','Titik jemput yang Anda tentukan'],included:['Permintaan perjalanan satu arah sesuai rute pilihan.','Pilihan kendaraan disesuaikan dengan penumpang dan bagasi.','Koordinasi jadwal penjemputan bersama tim layanan.'],requirements:['Siapkan alamat jemput dan tujuan lengkap.','Untuk penjemputan bandara, cantumkan nomor penerbangan.','Tarif, kapasitas kendaraan, waktu tunggu, dan ketentuan perubahan dikonfirmasi tim Siiru.'],note:'Perjalanan pulang, tambahan pemberhentian, dan waktu tunggu perlu dikonfirmasi terpisah.',app:'Chat dengan driver dan koordinasikan titik jemput melalui Siiru App.',cta:'Atur perjalanan'},
 {id:'iftar',category:'sedekah-wakaf',name:'Sedekah paket iftar',tag:'KEBAIKAN DI MASJIDIL HARAM',image:'iftar-product.webp',icon:'heart',type:'product',productId:3721,city:'Masjidil Haram',unit:'per paket',url:'https://services.siiru.io/product/sedekah-iftar-at-masjidil-haram/',description:'Berbagi hidangan berbuka untuk jemaah. Pilih paket kontribusi sesuai niat baik Anda.',features:['Pilihan 1, 5, atau 10 paket','Distribusi program Ramadan','Rincian paket sebelum transaksi'],included:['Paket utama berisi kurma, yogurt, duqqah, roti, dan air Zamzam.','Tambahan makanan mengikuti paket resmi yang tersedia.','Penyaluran mengikuti periode program Ramadan.'],requirements:['Periksa periode penyaluran dan ketersediaan program.','Pilih varian paket di halaman transaksi resmi.','Pastikan detail kontribusi sebelum menyelesaikan pembayaran.'],note:'Pilihan menu tambahan dan jadwal penyaluran mengikuti ketentuan program.',app:'Ikuti perjalanan donasi dan dokumentasi penyaluran di Siiru App.',cta:'Pilih kontribusi'},
 {id:'mutawwif-ziarah',category:'mutawwif',name:'Pendamping ziarah',tag:'LEBIH DEKAT DENGAN SEJARAH',image:'kaaba-day.jpg',icon:'guide',type:'booking',city:'Makkah · Madinah',unit:'per layanan',description:'Kunjungi tempat bersejarah dengan pendampingan. Pilih kota dan sampaikan tujuan yang ingin dikunjungi.',features:['Pilihan Makkah atau Madinah','Tujuan sesuai kebutuhan grup','Terpisah dari pendampingan umrah'],included:['Permintaan pendampingan ziarah sesuai kota yang dipilih.','Diskusi tujuan dan kebutuhan grup sebelum penetapan jadwal.','Koordinasi bersama tim untuk lingkup layanan.'],requirements:['Tentukan kota, tanggal, dan jumlah peserta.','Cantumkan lokasi yang ingin dikunjungi.','Rute, durasi, pendamping, dan tarif mengikuti konfirmasi.'],note:'Tiket masuk dan transportasi perlu dikonfirmasi; tidak otomatis termasuk.',app:'Lanjutkan percakapan dengan mutawwif melalui Siiru App.',cta:'Rencanakan ziarah'},
 {id:'water',category:'sedekah-wakaf',name:'Sedekah air minum',tag:'SETEGUK KEBAIKAN',image:'water-product.webp',icon:'heart',type:'product',productId:4754,city:'Tanah Suci',unit:'per pilihan paket',url:'https://services.siiru.io/product/chilled-drinking-water-for-pilgrims-during-hajj/',description:'Bantu menyegarkan langkah jemaah melalui program distribusi air minum dingin di musim haji.',features:['Program air minum jemaah','Pilihan paket kontribusi','Mengikuti periode penyaluran'],included:['Kontribusi air minum melalui program Sabil Siiru.','Pilihan unit dan jumlah mengikuti katalog resmi.','Distribusi untuk jemaah pada periode program.'],requirements:['Periksa tanggal pelaksanaan dan status program.','Pilih jumlah paket di website transaksi resmi.','Harga akhir mengikuti mata uang dan paket yang dipilih.'],note:'Program bersifat musiman. Ketersediaan dapat berubah.',app:'Lihat pembaruan perjalanan donasi Anda di Siiru App.',cta:'Lihat program'},
 {id:'quran',category:'sedekah-wakaf',name:'Wakaf Al-Qur’an',tag:'KEBAIKAN YANG TERUS DIBACA',image:'quran-product.png',imageType:'product',icon:'book',type:'product',productId:641,city:'Tanah Suci',unit:'per unit',url:'https://services.siiru.io/product/alquran/',description:'Ambil bagian dalam penyediaan Al-Qur’an melalui program wakaf Siiru.',features:['Kontribusi berdasarkan unit','Rincian produk sebelum bayar','Dokumentasi melalui aplikasi'],included:['Kontribusi program wakaf Al-Qur’an.','Jumlah unit sesuai pilihan pada transaksi.','Penyaluran mengikuti ketentuan program resmi.'],requirements:['Tinjau spesifikasi dan ketersediaan pada detail resmi.','Tentukan jumlah unit kontribusi.','Simpan konfirmasi transaksi untuk referensi Anda.'],note:'Lokasi dan waktu penyaluran mengikuti keterangan program.',app:'Pantau perjalanan wakaf dan lihat dokumentasinya di Siiru App.',cta:'Pilih wakaf'},
 {id:'wheelchair',category:'sedekah-wakaf',name:'Wakaf kursi roda',tag:'MEMUDAHKAN LANGKAH SESAMA',image:'wheelchair-product.png',imageType:'product',icon:'heart',type:'product',productId:118,city:'Tanah Suci',unit:'per unit',url:'https://services.siiru.io/product/wheelchair/',description:'Dukung sarana mobilitas bagi jemaah yang membutuhkan melalui wakaf kursi roda.',features:['Wakaf sarana mobilitas','Kontribusi berdasarkan unit','Pembaruan melalui Siiru App'],included:['Kontribusi wakaf kursi roda melalui Siiru.','Jumlah unit sesuai transaksi yang dikonfirmasi.','Penyaluran sesuai program resmi.'],requirements:['Periksa spesifikasi kursi roda pada halaman resmi.','Pastikan jumlah unit yang ingin diwakafkan.','Periksa ketentuan dan ketersediaan sebelum pembayaran.'],note:'Wakaf kursi roda berbeda dengan pemesanan bantuan kursi roda untuk perjalanan pribadi.',app:'Pantau perkembangan wakaf melalui Siiru App.',cta:'Pilih wakaf'},
 {id:'qurban',category:'qurban-aqiqah',name:'Qurban & kebutuhan aqiqah',tag:'NIAT IBADAH, DIPERSIAPKAN BAIK',image:'qurban-product.webp',icon:'sun',type:'product',productId:226,city:'Sesuai program',unit:'per pilihan hewan',url:'https://services.siiru.io/product/qurban/',description:'Tinjau pilihan qurban dan persiapkan data peserta. Untuk aqiqah, konsultasikan kebutuhan dengan tim Siiru.',features:['Pilihan hewan sesuai program','Data peserta sebelum pelaksanaan','Aqiqah melalui konsultasi'],included:['Pilihan qurban dan spesifikasi mengikuti produk resmi.','Pelaksanaan dan distribusi mengikuti ketentuan program.','Kebutuhan aqiqah dikonfirmasi secara terpisah.'],requirements:['Periksa jenis hewan, periode, dan lokasi pelaksanaan.','Siapkan nama peserta sesuai kebutuhan program.','Konfirmasi rincian pelaksanaan sebelum transaksi.'],note:'Harga dan ketersediaan qurban tidak otomatis berlaku untuk aqiqah.',app:'Akses pembaruan layanan dan dokumentasi yang tersedia di Siiru App.',cta:'Lihat pilihan'},
 {id:'dam',category:'dam',name:'Konsultasi layanan dam',tag:'PAHAMI KEBUTUHAN TERLEBIH DAHULU',image:'kaaba.jpg',icon:'book',type:'consult',city:'Tanah Suci',unit:'sesuai kebutuhan',description:'Diskusikan kebutuhan dam dengan tim Siiru sebelum menentukan layanan dan pelaksanaannya.',features:['Konsultasi kebutuhan terlebih dahulu','Ketersediaan perlu dikonfirmasi','Belum tersedia untuk checkout'],included:['Permintaan informasi layanan dam kepada tim Siiru.','Konsultasi untuk menjelaskan kebutuhan Anda.'],requirements:['Sampaikan konteks kebutuhan dengan jelas.','Minta penjelasan ketentuan kepada pendamping yang kompeten.','Tunggu konfirmasi layanan dan proses pelaksanaannya.'],note:'Halaman ini tidak menetapkan kewajiban dam. Transaksi belum tersedia untuk layanan ini.',app:'Gunakan Siiru App untuk mengakses panduan dan pendampingan perjalanan.',cta:'Pelajari layanan'}
];
export const serviceFaqs=[
 ['Bisa bertransaksi tanpa mengunduh Siiru App?','Anda dapat meninjau layanan dan melanjutkan transaksi produk melalui website Siiru. Untuk layanan yang memerlukan penyesuaian, siapkan kebutuhan Anda lalu konfirmasikan dengan tim. Siiru App digunakan untuk pengalaman lanjutan seperti perjalanan donasi dan chat langsung dengan mutawwif atau driver.'],
 ['Apa perbedaan pemesanan layanan dan transaksi produk?','Mutawwif, ziarah, dan transportasi membutuhkan konfirmasi jadwal, cakupan, serta tarif. Sedekah, wakaf, dan qurban memiliki pilihan produk yang dapat dilanjutkan ke checkout resmi ketika tersedia. Permintaan booking belum merupakan konfirmasi pesanan.'],
 ['Kapan harga dan ketersediaan dipastikan?','Harga produk ditampilkan dari katalog resmi jika berhasil dimuat. Harga akhir, mata uang, varian, dan stok dikonfirmasi kembali di halaman transaksi. Tarif layanan personal dikonfirmasi tim berdasarkan kebutuhan Anda.'],
 ['Bagaimana melihat perjalanan donasi saya?','Gunakan Siiru App untuk mengikuti perjalanan donasi dan dokumentasi penyaluran. Simpan referensi transaksi Anda; tim Siiru dapat membantu jika transaksi belum terlihat di aplikasi.'],
 ['Bagaimana menghubungi mutawwif atau driver?','Percakapan langsung dengan mutawwif dan driver dilakukan melalui Siiru App. Sebelum pemesanan, tim layanan Siiru membantu konfirmasi kebutuhan, jadwal, dan harga.'],
 ['Bagaimana jika perlu mengubah atau membatalkan pesanan?','Hubungi tim Siiru dengan menyertakan referensi transaksi. Kebijakan perubahan, pembatalan, dan pengembalian dana mengikuti ketentuan layanan serta status pesanan; periksa sebelum membayar.']
];
