const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const base=process.env.SIIRU_TEST_URL||'http://localhost:5173';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 // Prevent real checkouts or messages during automated verification.
 await page.route('https://services.siiru.io/**',route=>route.abort());await page.route('https://wa.me/**',route=>route.abort());
 await page.route('**/api/products/*',route=>{const id=Number(route.request().url().split('/').pop());return route.fulfill({json:{id,price:id===641?55:20,currency:'SAR',inStock:id!==4754,purchasable:id!==4754,variable:[3721,226,4754].includes(id),checkedAt:'2026-09-10T00:00:00Z'}})});
 await page.goto(base+'/layanan',{waitUntil:'networkidle'});
 assert.equal(await page.locator('.svc-card').count(),9);
 await page.locator('[data-category-filter="mutawwif"]').click();assert.equal(await page.locator('.svc-card').count(),2);
 await page.locator('#service-search').fill('xyz123');assert.equal(await page.locator('.svc-card').count(),0);assert(await page.locator('#service-empty').isVisible());
 await page.locator('#reset-services').click();assert.equal(await page.locator('.svc-card').count(),9);
 await page.locator('#service-sort').selectOption('az');const names=await page.locator('.svc-card h3').allTextContents();assert.deepEqual(names,[...names].sort((a,b)=>a.localeCompare(b,'id')));
 await page.locator('[data-service-detail="transport-private"]').first().click();const dialog=page.locator('#service-dialog');await dialog.waitFor({state:'visible'});
 await dialog.locator('button[type="submit"]').click();assert.equal(await page.locator('#svc-handoff').count(),0);
 const future=new Date();future.setDate(future.getDate()+10);const date=future.toISOString().slice(0,10);
 await dialog.locator('[name="tanggal"]').fill(date);await dialog.locator('[name="jemput"]').fill('Terminal kedatangan JED');await dialog.locator('[name="tujuan"]').fill('Hotel di Makkah');
 await dialog.locator('[name="dari"]').selectOption('Makkah');await dialog.locator('[name="ke"]').selectOption('Makkah');await dialog.locator('button[type="submit"]').click();assert.match(await page.locator('#svc-form-error').textContent(),/berbeda/);
 await dialog.locator('[name="dari"]').selectOption('Bandara Jeddah');await dialog.locator('[name="catatan"]').fill('<img src=x onerror=alert(1)> & lansia');await dialog.locator('button[type="submit"]').click();
 assert.equal(await page.locator('#svc-handoff').getAttribute('href'),null);assert.equal(await dialog.locator('img[src="x"]').count(),0);await page.locator('#svc-consent').check();const wa=new URL(await page.locator('#svc-handoff').getAttribute('href'));assert.equal(wa.hostname,'wa.me');assert.match(wa.searchParams.get('text'),/Terminal kedatangan JED/);assert.match(wa.searchParams.get('text'),/lansia/);
 await page.locator('#svc-back').click();assert.equal(await dialog.locator('[name="jemput"]').inputValue(),'Terminal kedatangan JED');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));await page.waitForFunction(()=>!new URL(location.href).searchParams.has('detail'));assert.equal(new URL(page.url()).searchParams.has('detail'),false);
 await page.locator('[data-service-detail="quran"]').first().click();await dialog.locator('[data-quantity="1"]').click();assert.match(await page.locator('#svc-subtotal').textContent(),/110/);await dialog.locator('button[type="submit"]').click();await page.locator('#svc-consent').check();const checkout=new URL(await page.locator('#svc-handoff').getAttribute('href'));assert.equal(checkout.origin,'https://services.siiru.io');assert.equal(checkout.pathname,'/checkout/');assert.equal(checkout.searchParams.get('add-to-cart'),'641');assert.equal(checkout.searchParams.get('quantity'),'2');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));
 await page.locator('[data-service-detail="water"]').first().click();assert.equal(await dialog.locator('button[type="submit"]').count(),0);assert.match(await dialog.locator('.svc-availability').textContent(),/Belum tersedia/);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));
 await page.locator('[data-service-detail="iftar"]').first().click();await dialog.locator('button[type="submit"]').click();await page.locator('#svc-consent').check();const variable=new URL(await page.locator('#svc-handoff').getAttribute('href'));assert.match(variable.pathname,/sedekah-iftar/);assert.equal(variable.searchParams.has('add-to-cart'),false);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));
 await page.locator('[data-service-detail="dam"]').first().click();assert.equal(await dialog.locator('button[type="submit"]').count(),0);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));
 await page.locator('[data-service-detail="mutawwif-umrah"]').first().click();await dialog.locator('[data-service-app]').click();assert(await page.locator('#download').isVisible());assert.equal(await dialog.isVisible(),false);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));
 await page.goto(base+'/layanan?kategori=sedekah-wakaf&detail=quran',{waitUntil:'networkidle'});assert(await dialog.isVisible());await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));assert.equal(await page.locator('.svc-card').count(),4);
 await page.locator('[data-category-filter="semua"]').click();await page.locator('#budget-form [name="people"]').selectOption('4');assert.match(await page.locator('#budget-total').textContent(),/52.000.000/);
 for(const width of [375,390,640,768,1024,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'page overflow '+width);await page.locator('[data-service-detail="transport-private"]').first().click();assert.equal(await dialog.evaluate(el=>el.scrollWidth>el.clientWidth+1),false,'dialog overflow '+width);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));}
 await page.route('**/api/products/*',route=>route.fulfill({status:503,json:{error:'Temporarily unavailable'}}));await page.reload({waitUntil:'networkidle'});await page.locator('[data-service-detail="quran"]').first().click();await dialog.locator('.svc-retry').waitFor();assert.equal(await dialog.locator('button[type="submit"]').count(),0);assert(await dialog.getByRole('link',{name:'Lihat di Siiru'}).isVisible());await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]')&&!new URL(location.href).searchParams.has('detail'));
 assert.deepEqual(errors,[]);console.log('PASS: catalogue, search, filters, sorting, booking validation, safe review, draft edit, official checkout links, unavailable products, app handoff, deep links, estimator, 6 widths, API failure. No transactions executed.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
